### ISSUE TITLE
Publish a Docker image on release

### ISSUE THREAD

**Issue by dwj300** [linkerd/linkerd-await#12]
Could you possible release a new image?

**Comment by olix0r** [comment]
We haven't been releasing these to Dockerhub for a while, I think. The updated docs use:

```
RUN curl -sSLo /tmp/linkerd-await https://github.com/olix0r/linkerd-await/releases/download/release%2F${LINKERD_AWAIT_VERSION}/linkerd-await
```

Does this work? Or are you reliant on docker images?

**Comment by dwj300** [comment]
We were planning on using an initContainer for one of our use cases since we don't own the main image, thus can't install curl in it. So sort of, but we can also just build it ourselves from the release

**Comment by olix0r** [comment]
For now, I'd recommend building a one-off image. I'd like to promote this repo into the Linkerd repo org as an official project, and in doing so we should automate publishing docker images (for all of our support architectures) to the release process.

I've updated the issue description to capture this.

**Comment by olix0r** [comment]
Now that we bundle the await utility in the proxy container image, I don't think this is needed anymore. Please let us know if this isn't true.
