### ISSUE TITLE
Disable readiness check skipped logging

### ISSUE THREAD

**Issue by Crevil** [linkerd/linkerd-await#41]
Currently when linkerd-await detects a reason to be disabled it will print a log line like below (https://github.com/linkerd/linkerd-await/blob/main/src/main.rs#L63).

```
Linkerd readiness check skipped: a reason
```

We are currently running an opt-in deployment of linkerd and would like to run linkerd-await conditionally according to user's options. As this log line is written no matter what, we cannot avoid notifying users who have not opted in to linkerd with the log lines.

A possible solution would be to add a `--silent` flag to disable the log line. As there are no structured logging it would however be nice to still see the errors in this case so maybe the `silent` wording is not that good. WDYT?

We'd be happy to provide the implementation if this is something you find valuable.

**Comment by adleong** [comment]
Hi @Crevil!  Can you help me understand the scenario a bit more?  As far as I understand, this log line is printed to the linkerd-await container logs.  Can users who don't want to see this log line, just not look at the container logs for linkerd-await?  Or do you have tooling which is aggregating those logs?

**Comment by Crevil** [comment]
Sure.

The platform collects all logs from our containers automatically. As linkerd-await is built into our application docker images the logs will originate from the same container. Developers are used to rely on any logs from their application container is something they themselves produce.

As we want to enable Linkerd transparently for our developers these log lines confuses the clearness of logs.

Does that clearify?

**Comment by adleong** [comment]
Yes, @Crevil, that's very helpful!  Makes perfect sense.

**Comment by Crevil** [comment]
Thank you so much @olix0r 🙌
